### ISSUE TITLE
World Gen problems when leaving spawn

### ISSUE THREAD

**Issue by jkoukoul** [Thunderrock424242/Wilderness-Odyssey#10]
**Describe the bug**
World gen is problematic where spawn protection ends. (By spawn protection i mean the radius in which players cant break blocks in order to protect the spawn from griefers)

**Expected behavior**
The world should continue to generate smoothly rather than have a big height difference

**Screenshots**
![image](https://github.com/Thunderrock424242/Wilderness-Odyssey/assets/157519504/6a66f7fd-aaa8-471e-bc0f-9788c1abe17c)
![2024-05-23_15 58 20](https://github.com/Thunderrock424242/Wilderness-Odyssey/assets/157519504/6d630685-05a3-4efe-a2e4-092f638759b8)

**Extra Note**
It can be seen from the map as well that world gen is bugged

**Comment by Thunderrock424242** [comment]
@jkoukoul Actually this is due to the fact the starting village was made my hand and had to be placed into the world. Nothing I can do about it for now till we work on it in the future. I will leave this open and put it into the backlog.

**Comment by Thunderrock424242** [comment]
i will try to fix this during the 1.21 port if not during 1.21

**Comment by Thunderrock424242** [comment]
might have to tweak some things to push it into the ground just don't dig down next to it lol

**Comment by Thunderrock424242** [comment]
Still being adjusted

**Comment by Thunderrock424242** [comment]
this issue will be converted into lore.
"long ago a meteor landed and when it hit it created mountains around the impact site and there the player spawned and a village was around it but mystery lies hidden underneath the site."

**Comment by Thunderrock424242** [comment]
this will be closed since it will be converted into lore
