### ISSUE TITLE
Land Claiming

### ISSUE THREAD

**Issue by jkoukoul** [Thunderrock424242/Wilderness-Odyssey#13]
**Describe the bug**
You can claim 500 chunks with ftb claim, thats too **MUCH**. WIth those 500 chunks you can also claim spawn for some reason? (You cant break spawn blocks if you claim the spawn tho)

**Expected behavior**
Should be lowered to 25 chunks 

**Screenshots**
![2024-05-23_16 10 51](https://github.com/Thunderrock424242/Wilderness-Odyssey/assets/157519504/d6a8753b-6509-498d-b166-93364ab77aac)

**Additional context**
The screenshot shows only 178 chunks, imagine what 500 would look like...

**Comment by Thunderrock424242** [comment]
Thanks for the info

**Comment by Thunderrock424242** [comment]
The above comit fixed this

**Comment by Thunderrock424242** [comment]
fixed issue each player can now claim up to 50 chunks each but the world will only allow 200 in total
