### ISSUE TITLE
Spawn Issue

### ISSUE THREAD

**Issue by jkoukoul** [Thunderrock424242/Wilderness-Odyssey#14]
**Describe the bug**
The time you first spawn in the world, every grass and branch in the spawn area breaks resulting in a lot of dropped seeds and sticks which causes quite some lag 

**Expected behavior**
Grass and branches shouldnt when loading in

**Screenshots**
![2024-06-02_21 03 16](https://github.com/Thunderrock424242/Wilderness-Odyssey/assets/157519504/0efd833e-1760-4c02-bcb9-fa111d8675f3)

Note: I believe this is happening because the spawn village spawns in and while replacing the previous land it breaks the grass.

**Comment by Thunderrock424242** [comment]
i added something that will detect the mass amount of things dropped and remove them but also I will be trying to fix this

**Comment by Thunderrock424242** [comment]
Will be fixed when ported to neoforge but it's basically fixed rn

**Comment by Thunderrock424242** [comment]
gonna try to fix this in the upcoming api

**Comment by Thunderrock424242** [comment]
will be fixed in our api 1.0.0 v 1.21.1
