### ISSUE TITLE
Darkstar (Sword) bug

### ISSUE THREAD

**Issue by jkoukoul** [Thunderrock424242/Wilderness-Odyssey#4]
**Describe the bug**
When at mid range m1 ability is quite incosistent. (even tho its still in range, it doesnt do damage sometimes)
**Expected behavior**
When pressing m1 spawns spikes out of the ground damaging anyone in their way.
**Screenshots**

Uploading MedalTVMinecraft20240121113311.mp4…

**Comment by Thunderrock424242** [comment]
What mod is the dark star sword from

**Comment by Thunderrock424242** [comment]
fixed in newer version coming soon
