### ISSUE TITLE
Temperature update 

### ISSUE THREAD

**Issue by jkoukoul** [Thunderrock424242/Wilderness-Odyssey#5]
**Describe it**
When you are near lava (or any big enough heat source), after 5 seconds or so your camera starts blurring and shaking due to too much heat, i havent tested if its the same with cold temperatures. 

**Expected behavior**
I believe that its an interesting aspect, since it punishes reckless moves without the proper equipment however it needs to be nerfed a bit and maybe add armor that helps with combating that effect because when you go into caves for mining you cant go near lava at all without your screen getting messed up.

**Comment by Thunderrock424242** [comment]
Will be fixed next update

**Comment by Thunderrock424242** [comment]
still working on this

**Comment by Thunderrock424242** [comment]
so this will kinda be a feature I am in the process of making custom effects like warmth or coldness for different armors while this will take a while I will try to get some in 1.3.0

**Comment by Thunderrock424242** [comment]
adding on to this there will be custom biome temps if I deem the biome is too hot or cold this will mainly fix the nether and other things.

**Comment by jkoukoul** [comment]
Alright, tell me when custom biome temps are out so I can test it 👍

**Comment by Thunderrock424242** [comment]
> Alright, tell me when custom biome temps are out so I can test it 👍

this may not be a thing, prob only for the nether tho

**Comment by Thunderrock424242** [comment]
This will be worked for a while no estimate

**Comment by Thunderrock424242** [comment]
converting this this will be its own update and be added to biomes and worlds

**Comment by Thunderrock424242** [comment]
@jkoukoul I am assigning you this for 1.21.1 to do more information when 1.21.1 comes out

**Comment by Thunderrock424242** [comment]
closed since new update is coming soon
