### ISSUE TITLE
Wood Pickaxe doesnt work as intented

### ISSUE THREAD

**Issue by jkoukoul** [Thunderrock424242/Wilderness-Odyssey#9]
**Describe the bug**
Wood pickaxe breaks stone blocks slowly and when you break it, the block doesnt drop

**Expected behavior**
Wood pickaxe should be able to break faster and drop the block

Possible Solution: 
Pickaxe info says that the wood pick has 1 harvest level so probably stone block has a higher harvest level for some reason possibly has to do with a mod that alters its harvest level

**Comment by Thunderrock424242** [comment]
can you test this for me?

**Comment by jkoukoul** [comment]
Remind me another time please, I just got off.

**Comment by Thunderrock424242** [comment]
ok

**Comment by Thunderrock424242** [comment]
@jkoukoul can you get video footage of this pls

**Comment by Thunderrock424242** [comment]
Video link: [is this](https://medal.tv/games/minecraft/clips/i4e8sWGVu1XfXr7_r/d1337XzYtGmr?invite=cr-MSxtRm0sMjEzOTU5OTEwLA)

**Comment by Thunderrock424242** [comment]
will carefully monitor this as i build the revamp
